name: Build CI / CD
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  build_tests_Unit:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the repository
      uses: actions/checkout@v4
    - name: Use Node.js 20.x
      uses: actions/setup-node@v4
      with:
        node-version: 20.x
        cache: 'npm'
    - name: install npm dependencies
      run: npm install
    - name: Run Unit tests
      run: npm run test:unit
    - name: Display softuni username
      run: echo "sdplamen"
  build_UI_tests:
    needs: build_tests_Unit
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the repository
      uses: actions/checkout@v4
    - name: Use Node.js 20.x
      uses: actions/setup-node@v4
      with:
        node-version: 20.x
        cache: 'npm'
    - name: install npm dependencies
      run: npm install
    - name: Install Playwirght Browsers
      run: npx playwright install
    - name: Start the Aplication
      run: npm start &
    - name: Run UI tests
      run: npm run test:ui
  deploy:
    needs: build_UI_tests
    runs-on: ubuntu-latest
    steps:
      - name: Deploy in production
        uses: JorgeLNJunior/render-deploy@v1.4.4
        with:
          service_id: ${{ secrets.MY_RENDER_SERVICE }}
          api_key: ${{ secrets.MY_RENDER_API_KEY }}
          wait_deploy: true
